/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 man.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Man(props) {
  const { nodes, materials } = useGLTF('/models/man.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube137.geometry} material={materials['sofa.001']} position={[3.085, 2.274, 4.33]} rotation={[0, 0.364, 0]} scale={[0.882, 0.882, 0.757]} />
      <mesh geometry={nodes.Cube076.geometry} material={materials.man} position={[2.178, 4.259, 2.352]} rotation={[Math.PI, -0.357, Math.PI]} scale={[0.878, 1.261, 1.21]} />
    </group>
  )
}

useGLTF.preload('/models/man.gltf')
