/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 manRoom.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Man_Room(props) {
  const { nodes, materials } = useGLTF('/models/manRoom.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} position={[5.673, 4.498, 9.259]} rotation={[0, Math.PI / 2, 0]} scale={[0.707, 1, 1]} />
      <mesh geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[10.922, 2.126, 11.039]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube103.geometry} material={nodes.Cube103.material} position={[-1.704, 0.144, 0.044]} scale={[19.828, 0.242, 11.519]} />
      <mesh geometry={nodes.Cube104.geometry} material={materials['Material.077']} position={[15.056, 7.634, -0.219]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-7.65, -0.308, -14.467]} />
      <mesh geometry={nodes.Cube105.geometry} material={materials['Material.078']} position={[-7.522, 2.948, -5.464]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.431, -0.174, -17.177]} />
      <mesh geometry={nodes.Cube106.geometry} material={nodes.Cube106.material} position={[-2.303, 15.43, -0.269]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-17.086, -0.201, -14.467]} />
      <mesh geometry={nodes.Cube107.geometry} material={nodes.Cube107.material} position={[3.481, 3.19, -5.192]} rotation={[0, -0.4, 0]} scale={[0.421, 0.661, 1.197]} />
      <mesh geometry={nodes.Cube108.geometry} material={nodes.Cube108.material} position={[3.481, 3.546, -5.192]} rotation={[-Math.PI, 0.4, 0]} scale={[-0.088, -0.661, -0.982]} />
      <mesh geometry={nodes.Cube109.geometry} material={nodes.Cube109.material} position={[-7.598, 3.091, -5.953]} scale={[2.146, 0.71, 4.741]} />
      <mesh geometry={nodes.Cube110.geometry} material={nodes.Cube110.material} position={[-7.598, 1.805, -5.953]} scale={[1.846, 1.818, 4.475]} />
      <mesh geometry={nodes.Cube111.geometry} material={nodes.Cube111.material} position={[14.666, 9.888, 8.904]} rotation={[0, Math.PI / 2, 0]} scale={[1.637, 1.295, 0.166]} />
      <mesh geometry={nodes.Cube112.geometry} material={nodes.Cube112.material} position={[8.761, 5.139, 9.554]} scale={[1.626, 0.142, 0.795]} />
      <mesh geometry={nodes.Cube113.geometry} material={nodes.Cube113.material} position={[2.499, 3.413, -8.957]} rotation={[Math.PI, -1.366, Math.PI]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube114.geometry} material={nodes.Cube114.material} position={[1.753, 6.057, 10.398]} rotation={[0.006, 0, Math.PI / 2]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube115.geometry} material={nodes.Cube115.material} position={[8.761, 5.393, 9.745]} scale={[0.574, 0.236, 0.166]} />
      <mesh geometry={nodes.Cube116.geometry} material={nodes.Cube116.material} position={[8.761, 7.236, 9.454]} scale={[2.291, 1.405, 0.166]} />
      <mesh geometry={nodes.Cube119.geometry} material={nodes.Cube119.material} position={[-1.691, 8.077, 9.75]} scale={[0.801, 1.416, 0.828]}>
        <mesh geometry={nodes.Cube122.geometry} material={nodes.Cube122.material} position={[0, -1.472, -0.07]} scale={[0.133, 3.881, 0.133]} />
        <mesh geometry={nodes.Cube125.geometry} material={nodes.Cube125.material} position={[0, -5.249, -0.034]} scale={[0.675, 0.226, 0.675]} />
      </mesh>
      <mesh geometry={nodes.Cube127.geometry} material={nodes.Cube127.material} position={[14.977, 9.418, 0.372]} scale={[0.414, 4.009, 6.152]} />
      <mesh geometry={nodes.Cube128.geometry} material={nodes.Cube128.material} position={[-2.487, 2.858, 7.153]} rotation={[0, -0.242, 0]} scale={[0.741, 2.466, 1.36]} />
      <mesh geometry={nodes.Cube129.geometry} material={nodes.Cube129.material} position={[-2.573, 4.021, 7.052]} rotation={[0, -0.257, 0]} scale={[0.121, 0.586, 0.64]} />
      <mesh geometry={nodes.Cube130.geometry} material={nodes.Cube130.material} position={[1.249, 6.057, 10.398]} rotation={[0.006, 0, Math.PI / 2]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube131.geometry} material={nodes.Cube131.material} position={[2.256, 6.057, 10.398]} rotation={[0.006, 0, Math.PI / 2]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube132.geometry} material={nodes.Cube132.material} position={[-1.847, 8.048, -9.525]} scale={[2.674, 8.187, 1.878]} />
      <mesh geometry={nodes.Cube133.geometry} material={nodes.Cube133.material} position={[3.473, 2.127, -5.115]} rotation={[0, 1.138, 0]} scale={[1.392, 0.665, 1.44]}>
        <mesh geometry={nodes.Cube134.geometry} material={nodes.Cube134.material} position={[-0.448, -1.105, -0.477]} scale={[0.227, 1.95, 0.227]} />
      </mesh>
      <mesh geometry={nodes.Cube135.geometry} material={nodes.Cube135.material} position={[-7.598, 4.179, -4.198]} scale={[0.491, 0.862, 0.506]} />
      <mesh geometry={nodes.Cube136.geometry} material={nodes.Cube136.material} position={[-7.598, 4.179, -6.607]} rotation={[0, 0.452, 0]} scale={[0.784, 0.804, 1.127]} />
      <mesh geometry={nodes.Cube137.geometry} material={nodes.Cube137.material} position={[1.951, 2.357, 4.172]} rotation={[0, 0.364, 0]} scale={[1, 1, 0.858]} />
      <mesh geometry={nodes.Cube138.geometry} material={nodes.Cube138.material} position={[-7.455, 4.477, -4.283]} rotation={[3.058, -0.067, -2.678]} scale={[0.029, 1, 0.029]} />
      <mesh geometry={nodes.Cube139.geometry} material={nodes.Cube139.material} position={[-7.455, 4.477, -4.081]} rotation={[-2.665, -0.067, -2.678]} scale={[0.02, 0.686, 0.02]} />
      <mesh geometry={nodes.Cube142.geometry} material={nodes.Cube142.material} position={[4.735, 6.128, 8.989]} rotation={[-2.72, 0.175, 1.498]}>
        <mesh geometry={nodes.Cube126.geometry} material={nodes.Cube126.material} position={[0.668, 0.041, -0.373]} rotation={[-3.13, -0.588, 1.579]} scale={[0.591, 0.591, 0.071]} />
      </mesh>
      <mesh geometry={nodes.Cube149.geometry} material={nodes.Cube149.material} position={[10.162, 1.65, 0.109]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube152.geometry} material={nodes.Cube152.material} scale={[4.814, 1.395, 3.969]} />
      </mesh>
      <mesh geometry={nodes.Cube150.geometry} material={nodes.Cube150.material} position={[3.738, 2.127, -9.55]} scale={[1.852, 1.821, 1.915]} />
      <mesh geometry={nodes.Cube151.geometry} material={materials['Material.091']} position={[-7.522, 2.948, 17.831]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.431, -0.174, -17.177]} />
      <mesh geometry={nodes.Cube161.geometry} material={nodes.Cube161.material} position={[4.677, 5.526, 9.537]} rotation={[-0.177, -0.195, -0.035]} scale={[0.591, 0.591, 0.071]} />
      <mesh geometry={nodes.Cube162.geometry} material={nodes.Cube162.material} position={[-4.84, 0.644, 4.824]} scale={[0.541, 0.32, 0.559]} />
      <mesh geometry={nodes.Cube163.geometry} material={nodes.Cube163.material} position={[-4.84, 5.993, 4.794]} scale={[0.107, 5.495, 0.11]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} position={[3.527, 5.577, 9.893]} rotation={[Math.PI, -1.035, Math.PI]} scale={0.896}>
        <mesh geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} position={[-0.069, 0.945, -0.498]} rotation={[-1.446, 1.445, 2.641]} scale={[1, 1, 0.376]} />
        <mesh geometry={nodes.Plane013.geometry} material={nodes.Plane013.material} position={[0.024, 1.027, 0.697]} rotation={[-1.207, -1.437, -0.008]} scale={[1, 1, 0.376]} />
        <mesh geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} position={[0.627, 1.324, 0.042]} rotation={[0, 0, 1.427]} scale={[1, 1, 0.376]} />
      </mesh>
      <mesh geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} position={[-7.455, 4.976, -3.921]} scale={0.338} />
      <mesh geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} position={[-7.08, 5.397, -4.394]} rotation={[0, 0, -0.293]} scale={0.408} />
      <mesh geometry={nodes.Plane011.geometry} material={nodes.Plane011.material} position={[10.156, 3.988, -1.504]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Plane015.geometry} material={nodes.Plane015.material} position={[13.631, 6.946, 9.884]} rotation={[0, 0, 1.427]} scale={[1, 1, 0.376]} />
      <mesh geometry={nodes.Plane016.geometry} material={nodes.Plane016.material} position={[13.028, 6.649, 10.539]} rotation={[-1.207, -1.437, -0.008]} scale={[1, 1, 0.376]} />
      <mesh geometry={nodes.Plane017.geometry} material={nodes.Plane017.material} position={[12.935, 6.567, 9.343]} rotation={[-1.446, 1.445, 2.641]} scale={[1, 1, 0.376]} />
      <mesh geometry={nodes.Cube075.geometry} material={nodes.Cube075.material} position={[0.652, 7.75, 2.035]} rotation={[Math.PI, -0.357, 3.063]} scale={[1.175, 1.28, 0.94]} />
      <mesh geometry={nodes.Cube076.geometry} material={nodes.Cube076.material} position={[0.924, 4.608, 1.929]} rotation={[Math.PI, -0.357, Math.PI]} scale={[0.995, 1.43, 1.372]} />
      <mesh geometry={nodes.Cube089.geometry} material={nodes.Cube089.material} position={[0.657, 7.75, 2.048]} rotation={[Math.PI, -0.357, 3.063]} scale={[1.258, 1.28, 1.007]} />
      <mesh geometry={nodes.Cube091.geometry} material={nodes.Cube091.material} position={[-0.278, 7.462, 2.381]} rotation={[Math.PI, -0.357, Math.PI]} scale={[0.211, 0.212, 0.212]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={nodes.Cylinder012.material} position={[0.386, 7.764, 1.276]} rotation={[3.131, -0.355, 1.379]} scale={[0.291, 0.332, 0.247]} />
    </group>
  )
}

useGLTF.preload('/models/manRoom.gltf')
