/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Ground.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Ground-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[3.698, -15.807, -3.215]} rotation={[-Math.PI, 0, -Math.PI]} scale={[49.537, 0.331, 49.537]} />
      <mesh geometry={nodes.mesh_1.geometry} material={materials['Tree 1']} />
      <mesh geometry={nodes.mesh_1_1.geometry} material={materials['Mat.3']} />
    </group>
  )
}

useGLTF.preload('/Ground-transformed.glb')
