/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 womanRoom.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Woman_Room(props) {
  const { nodes, materials } = useGLTF('/models/womanRoom.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube124.geometry} material={materials['Material.004']} position={[-7.522, 2.948, 17.726]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.431, -0.174, -17.177]} />
      <mesh geometry={nodes.Cube140.geometry} material={nodes.Cube140.material} position={[-1.562, 2.237, -10.862]} />
      <mesh geometry={nodes.Cube141.geometry} material={nodes.Cube141.material} position={[5.095, 1.409, 2.401]} scale={[0.866, 0.783, 0.783]}>
        <mesh geometry={nodes.Cube123.geometry} material={nodes.Cube123.material} scale={[4.814, 1.395, 3.969]} />
      </mesh>
      <mesh geometry={nodes.Cube143.geometry} material={nodes.Cube143.material} position={[2.51, 10.214, -10.821]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cube144.geometry} material={nodes.Cube144.material} position={[1.103, 2.483, -3.603]} rotation={[-Math.PI, 1.119, -Math.PI]} scale={[1.422, 0.335, 1.494]} />
      <mesh geometry={nodes.Cube145.geometry} material={nodes.Cube145.material} position={[0.777, 1.447, -2.544]} rotation={[-Math.PI, 1.119, -Math.PI]} scale={[0.232, 1.139, 0.232]} />
      <mesh geometry={nodes.Cube146.geometry} material={nodes.Cube146.material} position={[0.869, 4.294, -9.388]} />
      <mesh geometry={nodes.Cube147.geometry} material={nodes.Cube147.material} position={[-1.119, 9.572, -10.717]} scale={[1.07, 0.785, 0.685]} />
      <mesh geometry={nodes.Cube148.geometry} material={nodes.Cube148.material} position={[0.826, 5.078, -8.271]} scale={[1.299, 0.461, 0.831]} />
      <mesh geometry={nodes.Cube154.geometry} material={nodes.Cube154.material} position={[13.049, 2.542, -4.589]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube155.geometry} material={nodes.Cube155.material} position={[13.049, 8.447, 8.478]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube156.geometry} material={nodes.Cube156.material} position={[11.672, 3.164, -3.486]} scale={[1, 0.36, 1.224]} />
      <mesh geometry={nodes.Cube157.geometry} material={nodes.Cube157.material} position={[11.672, 5.569, -8.684]} scale={[1, 0.841, 1.224]} />
      <mesh geometry={nodes.Cube158.geometry} material={nodes.Cube158.material} position={[11.672, 4.766, -3.517]} scale={[0.414, 0.115, 0.507]} />
      <mesh geometry={nodes.Cube159.geometry} material={nodes.Cube159.material} position={[11.672, 6.189, -3.517]} scale={[0.414, 0.74, 0.507]} />
      <mesh geometry={nodes.Cube160.geometry} material={nodes.Cube160.material} position={[14.977, 9.418, 0.266]} scale={[0.414, 4.009, 6.152]} />
      <mesh geometry={nodes.Cube164.geometry} material={nodes.Cube164.material} position={[11.672, 5.503, -3.517]} scale={[0.078, 0.74, 0.095]} />
      <mesh geometry={nodes.Cube165.geometry} material={nodes.Cube165.material} position={[4.088, 2.88, 8.799]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube166.geometry} material={nodes.Cube166.material} position={[4.088, 1.23, 8.799]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube167.geometry} material={nodes.Cube167.material} position={[3.295, 1.937, 7.502]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube168.geometry} material={nodes.Cube168.material} position={[-2.653, 1.789, 3.202]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube169.geometry} material={nodes.Cube169.material} position={[-3.811, 1.204, 5.214]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube170.geometry} material={nodes.Cube170.material} position={[14.666, 9.888, 8.798]} rotation={[0, Math.PI / 2, 0]} scale={[1.637, 1.295, 0.166]} />
      <mesh geometry={nodes.Cube171.geometry} material={nodes.Cube171.material} position={[-2.653, 0.701, -1.189]} rotation={[0, Math.PI / 2, 0]} scale={[0.454, 1, 0.673]} />
      <mesh geometry={nodes.Cube172.geometry} material={nodes.Cube172.material} position={[-6.316, 0.701, 3.188]} rotation={[0, Math.PI / 2, 0]} scale={[0.454, 1, 0.673]} />
      <mesh geometry={nodes.Cube175.geometry} material={nodes.Cube175.material} position={[-2.303, 15.43, -0.375]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-17.086, -0.201, -14.467]} />
      <mesh geometry={nodes.Cube176.geometry} material={materials['Material.010']} position={[-7.522, 2.948, -5.57]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.431, -0.174, -17.177]} />
      <mesh geometry={nodes.Cube177.geometry} material={materials['Material.066']} position={[15.056, 7.634, -0.325]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-7.65, -0.308, -14.467]} />
      <mesh geometry={nodes.Cube178.geometry} material={nodes.Cube178.material} position={[-1.704, 0.144, -0.061]} scale={[19.828, 0.242, 11.519]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} position={[-2.899, 2.454, 3.807]} scale={[0.35, 0.391, 0.35]} />
      <mesh geometry={nodes.Plane018.geometry} material={nodes.Plane018.material} position={[6.492, 3.24, 2.396]} scale={[0.866, 0.783, 0.783]} />
      <mesh geometry={nodes.Cube120.geometry} material={nodes.Cube120.material} position={[0.855, 7.242, -3.587]} rotation={[Math.PI, -0.341, Math.PI]} scale={[0.195, 0.203, 0.093]} />
      <mesh geometry={nodes.Cube153.geometry} material={nodes.Cube153.material} position={[1.315, 4.31, -3.835]} rotation={[Math.PI, -0.341, Math.PI]} scale={[0.95, 1.254, 0.817]} />
      <mesh geometry={nodes.Cube173.geometry} material={nodes.Cube173.material} position={[1.563, 7.56, -3.826]} rotation={[3.114, -0.34, 3.059]} scale={[0.89, 1.226, 0.71]} />
      <mesh geometry={nodes.Cube179.geometry} material={nodes.Cube179.material} position={[-1.276, 1.527, -3.048]} rotation={[-0.026, 0.405, -0.276]} scale={[0.223, 1.08, 0.223]} />
      <mesh geometry={nodes.Cube180.geometry} material={nodes.Cube180.material} position={[-0.886, 1.621, -2.217]} rotation={[-0.026, 0.405, -0.276]} scale={[0.223, 1.08, 0.223]} />
      <mesh geometry={nodes.Cube181.geometry} material={nodes.Cube181.material} position={[1.563, 7.589, -3.826]} rotation={[3.114, -0.34, 3.059]} scale={[0.89, 1.226, 0.71]} />
      <mesh geometry={nodes.Cylinder014.geometry} material={nodes.Cylinder014.material} position={[1.351, 7.272, -4.38]} rotation={[2.796, 0.064, 1.394]} scale={[0.278, 0.307, 0.228]} />
      <mesh geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} position={[1.959, 8.633, -3.907]} rotation={[Math.PI, -0.341, Math.PI]} scale={0.442} />
    </group>
  )
}

useGLTF.preload('/models/womanRoom.gltf')
