/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 test_sofa.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Test_sofa(props) {
  const { nodes, materials } = useGLTF('/models/test_sofa.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube044.geometry} material={materials.lightmap} position={[1.707, 3.042, -10.536]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.844} />
    </group>
  )
}

useGLTF.preload('/models/test_sofa.gltf')
