/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 first_room.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/first_room.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.041']} position={[-7.522, 2.948, 17.757]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.431, -0.174, -17.177]} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[-4.84, 2.127, -9.624]} scale={[1.852, 1.821, 1.915]} />
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[0.2, 8.673, 10.161]} scale={[4.473, 8.315, 1.588]} />
      <mesh geometry={nodes.Cube037.geometry} material={nodes.Cube037.material} position={[-1.409, 1.204, -3.709]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.316, 0.869, 0.316]} />
      <mesh geometry={nodes.Cube040.geometry} material={nodes.Cube040.material} position={[0.604, 2.332, -2.551]} rotation={[-Math.PI, 0, -Math.PI]} scale={[2.761, 0.318, 1.729]} />
      <mesh geometry={nodes.Cube043.geometry} material={nodes.Cube043.material} position={[-1.895, 9.613, -11.435]} />
      <mesh geometry={nodes.Cube044.geometry} material={nodes.Cube044.material} position={[1.707, 3.319, -10.536]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.844}>
        <mesh geometry={nodes.Cube024.geometry} material={nodes.Cube024.material} position={[-0.032, -2.259, 2.621]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[-2.191, -2.871, 1.404]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} position={[2.117, -2.871, 1.404]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Cube042.geometry} material={nodes.Cube042.material} position={[-4.901, -2.322, 1.904]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.579, 0.729, 1]} />
        <mesh geometry={nodes.Cube045.geometry} material={nodes.Cube045.material} position={[4.784, -2.322, 1.904]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.579, 0.729, 1]} />
      </mesh>
      <mesh geometry={nodes.Cube046.geometry} material={materials['Material.042']} position={[14.524, 9.07, -4.918]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-5.379, -0.308, -3.709]} />
      <mesh geometry={nodes.Cube048.geometry} material={nodes.Cube048.material} position={[2.83, 7.821, -11.435]} scale={[3.794, 1.352, 1]} />
      <mesh geometry={nodes.Cube049.geometry} material={nodes.Cube049.material} position={[7.265, 1.32, -3.498]} scale={[1.348, 2.954, 1.348]} />
      <mesh geometry={nodes.Cube050.geometry} material={nodes.Cube050.material} position={[9.731, 2.802, 1.626]} rotation={[0, -0.866, -0.205]} />
      <mesh geometry={nodes.Cube051.geometry} material={nodes.Cube051.material} position={[10.65, 0.447, 1.155]} rotation={[0, -0.866, 0]} scale={[2.138, 0.187, 0.185]} />
      <mesh geometry={nodes.Cube052.geometry} material={nodes.Cube052.material} position={[11.401, 1.822, 2.026]} rotation={[-Math.PI, 0.866, 2.815]} scale={[0.143, 1, 0.143]} />
      <mesh geometry={nodes.Cube053.geometry} material={nodes.Cube053.material} position={[9.948, 1.81, 0.317]} rotation={[Math.PI, 0.866, -2.679]} scale={[0.143, 1, 0.143]} />
      <mesh geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} position={[8.429, 1.81, 1.608]} rotation={[Math.PI, 0.866, -2.679]} scale={[0.143, 1, 0.143]} />
      <mesh geometry={nodes.Cube055.geometry} material={nodes.Cube055.material} position={[9.882, 1.822, 3.317]} rotation={[-Math.PI, 0.866, 2.815]} scale={[0.143, 1, 0.143]} />
      <mesh geometry={nodes.Cube056.geometry} material={nodes.Cube056.material} position={[9.131, 0.447, 2.446]} rotation={[0, -0.866, 0]} scale={[2.138, 0.187, 0.185]} />
      <mesh geometry={nodes.Cube059.geometry} material={materials['Material.069']} position={[14.524, 9.07, 5.071]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-5.379, -0.308, -3.709]} />
      <mesh geometry={nodes.Cube061.geometry} material={nodes.Cube061.material} position={[15.419, 1.855, -0.647]} scale={[1.183, 1.797, 12.547]} />
      <mesh geometry={nodes.Cube062.geometry} material={nodes.Cube062.material} position={[9.219, 8.673, 10.161]} scale={[4.473, 8.315, 1.588]} />
      <mesh geometry={nodes.Cube064.geometry} material={nodes.Cube064.material} position={[13.175, 1.466, -8.911]} scale={[0.885, 1.2, 0.885]}>
        <mesh geometry={nodes.Cube072.geometry} material={nodes.Cube072.material} position={[0.11, 1.838, -0.043]} scale={[0.419, 1.126, 0.419]} />
        {/* <mesh geometry={nodes.Sphere004_1.geometry} material={nodes.Sphere004_1.material} position={[0.151, 3.495, 0]} scale={[1.978, 1.998, 1.978]} /> */}
      </mesh>
      <mesh geometry={nodes.Cube085.geometry} material={nodes.Cube085.material} position={[1.249, 2.876, -2.63]} rotation={[0, 1.066, 0]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube086.geometry} material={nodes.Cube086.material} position={[1.249, 3.413, -2.63]} rotation={[Math.PI, -1.366, Math.PI]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube087.geometry} material={nodes.Cube087.material} position={[-4.84, 3.141, -9.67]} scale={[0.541, 0.32, 0.559]} />
      <mesh geometry={nodes.Cube093.geometry} material={nodes.Cube093.material} position={[-4.84, 3.687, -9.7]} scale={[0.226, 0.656, 0.234]} />
      <mesh geometry={nodes.Cube098.geometry} material={nodes.Cube098.material} position={[-4.84, 4.292, -9.642]} scale={[0.68, 0.656, 0.704]} />
      <mesh geometry={nodes.Cube100.geometry} material={nodes.Cube100.material} position={[12.052, 10.151, 10.51]} scale={[1, 0.937, 0.513]} />
      <mesh geometry={nodes.Cube101.geometry} material={nodes.Cube101.material} position={[8.396, 12.622, 10.51]} scale={[1, 0.937, 0.513]} />
      <mesh geometry={nodes.Cube102.geometry} material={nodes.Cube102.material} position={[8.977, 4.78, 8.776]} scale={[1.314, 1, 1]} />
      <mesh geometry={nodes.Cube117.geometry} material={nodes.Cube117.material} position={[-2.303, 15.53, -0.343]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-17.086, -0.201, -14.467]} />
      <mesh geometry={nodes.Cube118.geometry} material={materials['Material.038']} position={[-7.522, 2.948, -5.538]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-9.431, -0.174, -17.177]} />
      <mesh geometry={nodes.Cube120.geometry} material={materials['Material.039']} position={[15.056, 7.634, -0.294]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-7.65, -0.308, -14.467]} />
      <mesh geometry={nodes.Cube121.geometry} material={nodes.Cube121.material} position={[-1.704, 0.144, -0.03]} scale={[19.828, 0.242, 11.519]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[10.888, 1.446, -10.238]} scale={[0.955, 4.232, 0.955]}>
        <mesh geometry={nodes.Cube078.geometry} material={nodes.Cube078.material} position={[0.394, 0.492, 0.657]} rotation={[2.822, -1.328, 2.176]} scale={[0.12, 0.806, 0.534]} />
        <mesh geometry={nodes.Cube080.geometry} material={nodes.Cube080.material} position={[-0.023, 0.492, -0.769]} rotation={[-1.393, 1.322, 0.844]} scale={[0.12, 0.761, 0.54]} />
        <mesh geometry={nodes.Cube083.geometry} material={nodes.Cube083.material} position={[0.539, 0.477, 0]} rotation={[0, 0, -0.512]} scale={[0.12, 0.761, 0.54]} />
        <mesh geometry={nodes.Cube084.geometry} material={nodes.Cube084.material} position={[-0.912, 0.477, 0]} rotation={[0, 0, 0.586]} scale={[0.114, 0.949, 0.54]} />
      </mesh>
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.070']} position={[13.84, 8.643, -8.258]} rotation={[0, 0, -Math.PI / 2]} scale={[5.715, 1, 1.536]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.003']} position={[13.84, 8.643, -1.92]} rotation={[0, 0, -Math.PI / 2]} scale={[5.715, 1, 1.536]} />
      <mesh geometry={nodes.Plane009.geometry} material={materials['Material.071']} position={[13.84, 8.643, 7.417]} rotation={[0, 0, -Math.PI / 2]} scale={[5.715, 1, 1.611]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.072']} position={[13.84, 8.643, 1.56]} rotation={[0, 0, -Math.PI / 2]} scale={[5.715, 1, 1.181]} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[10.653, 5.438, 2.494]} rotation={[-2.675, -1.075, -2.7]} />
      <mesh geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[9.994, 3.75, 2.225]} rotation={[-2.251, -0.907, -2.343]} scale={[1.138, 1.217, 1.138]} />
      <mesh geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} position={[8.885, 3.551, 1.736]} rotation={[-2.771, -0.931, -2.839]} scale={[0.46, 0.434, 1.138]} />
      <mesh geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[9.732, 3.442, 0.863]} rotation={[-2.943, -0.352, -2.972]} scale={[0.46, 0.434, 1.138]} />
    </group>
  )
}

useGLTF.preload('/models/first_room.gltf')
