/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 BoardForLightingmap.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useLoader} from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader.js'

export function BoardForLightingmap(props) {
  const { nodes, materials } = useGLTF('/models/BoardForLightingmap.gltf')

  const texture = useLoader(TextureLoader, '/texture/lightmap.png');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Board.geometry} material={materials['Material.006']} position={[-28.312, 0.15, -13.109]}>
      <meshStandardMaterial map={texture} attach="material" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/BoardForLightingmap.gltf')
