/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 playerRoom.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/playerRoom.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Potted_plants002.geometry} material={materials['Potted_plants.001']} position={[14.22, 10.864, -5.437]} rotation={[Math.PI / 2, 0, 2.777]} scale={0.057} />
      <mesh geometry={nodes.Potted_plants003.geometry} material={materials['Potted_plants.002']} position={[14.22, 10.673, -4.023]} rotation={[Math.PI / 2, 0, 2.777]} scale={0.057} />
      <mesh geometry={nodes.Cube069.geometry} material={materials['Material.008']} position={[14.239, 11.683, -4.054]} scale={[0.381, 0.618, 0.402]} />
      <mesh geometry={nodes.Potted_plants004.geometry} material={materials['Potted_plants.003']} position={[14.22, 10.673, -2.912]} rotation={[Math.PI / 2, 0, 2.777]} scale={[0.057, 0.057, 0.082]} />
      <mesh geometry={nodes.Cube070.geometry} material={materials['Material.033']} position={[14.239, 11.683, -2.943]} scale={[0.381, 1.01, 0.402]} />
      <mesh geometry={nodes.book.geometry} material={materials.bigbook} position={[-3.602, 0.471, -7.389]} rotation={[Math.PI / 2, 0, -0.365]} scale={[0.168, 0.2, 0.208]} />
      <mesh geometry={nodes.Cube094.geometry} material={materials['Material.052']} position={[0.445, 0.483, -6.498]} rotation={[0, 1.028, 0]} scale={[0.406, 0.103, 0.406]} />
      <group position={[-5.756, 1.199, -4.288]} rotation={[0.42, -0.281, 0.112]} scale={[0.594, 0.818, 0.077]}>
        <mesh geometry={nodes.Cube107.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Cube107_1.geometry} material={materials['Material.054']} />
      </group>
      <mesh geometry={nodes.Cube096.geometry} material={materials['Material.053']} position={[-5.795, 0.7, -4.179]} rotation={[-0.536, -0.262, -0.148]} scale={[0.324, 0.277, 0.037]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.056']} position={[-6.645, 0.429, -6.003]} scale={[0.532, 0.105, 0.532]}>
        <mesh geometry={nodes.Cube092.geometry} material={materials['Material.057']} position={[-0.006, 6.705, 0.037]} rotation={[-Math.PI, 0, 0]} scale={[-0.373, -6.277, -0.358]} />
      </mesh>
      <mesh geometry={nodes.Cube016.geometry} material={materials.chair} position={[7.125, 2.841, -4.713]} />
      <group position={[12.448, 5.059, 0.371]} scale={[0.539, 0.564, 0.539]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.yellow} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.black} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Material.002']} />
      </group>
      <group position={[11.656, 5.59, -7.335]} rotation={[0, 0.497, 0]} scale={[1, 1.132, 1.132]}>
        <mesh geometry={nodes.Cube087.geometry} material={materials['Material.095']} />
        <mesh geometry={nodes.Cube087_1.geometry} material={materials.clock} />
      </group>
      <group position={[12.167, 7.962, -3.558]}>
        <mesh geometry={nodes.Cube113.geometry} material={materials['Material.093']} />
        <mesh geometry={nodes.Cube113_1.geometry} material={materials['Material.094']} />
      </group>
      <mesh geometry={nodes.Cube071.geometry} material={materials['Material.007']} position={[-6.655, 5.864, 13.356]} rotation={[Math.PI, -1.553, Math.PI]} scale={[1, 1, 0.744]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[9.967, 5.084, -2.019]} rotation={[0, -0.512, -Math.PI / 2]} scale={[0.072, 1.761, 0.072]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[10.115, 5.084, -6.108]} rotation={[0, 0.827, -Math.PI / 2]} scale={[0.072, 1.761, 0.072]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[9.041, 5.08, -1.636]} rotation={[Math.PI, -0.299, Math.PI / 2]} scale={[0.072, 1.761, 0.072]} />
      <mesh geometry={nodes.Cube079.geometry} material={materials.book2} position={[9.231, 5.668, -8.068]} rotation={[0, 0.053, 0]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[13.004, 5.622, -7.527]} />
      <group position={[-6.067, 0.675, -7.386]} rotation={[3.05, 0.222, 1.295]} scale={[0.089, 2.177, 0.089]}>
        <mesh geometry={nodes.Cylinder022.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cylinder022_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder022_2.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.004']} position={[-4.547, 6.104, 13.287]} scale={[0.707, 3.134, 0.707]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.leaf} position={[13.921, 11.879, -5.455]} rotation={[3.006, -0.377, 2.814]} scale={[0.064, 0.597, 0.271]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.010']} position={[-4.192, 5.419, 11.207]} rotation={[-Math.PI, 0.303, -Math.PI]} scale={[-0.499, -0.067, -0.77]} />
      <mesh geometry={nodes.Cube077.geometry} material={materials['Material.005']} position={[-6.056, 6.126, 13.102]} rotation={[-0.536, -0.262, -0.148]} scale={[0.225, 0.193, 0.026]} />
      <group position={[-6.029, 6.469, 13.082]} rotation={[0.42, -0.281, 0.112]} scale={[0.413, 0.569, 0.053]}>
        <mesh geometry={nodes.Cube131.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube131_1.geometry} material={materials['Material.006']} />
      </group>
      <mesh geometry={nodes.Cube082.geometry} material={materials.drawer} position={[-7.322, 2.77, 12.503]} scale={[4.633, 2.585, 2.945]} />
      <group position={[14.182, 5.175, 40.023]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-2.344, -0.661, -1.471]}>
        <mesh geometry={nodes.Cube162.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Cube162_1.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Cube162_2.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube162_3.geometry} material={materials['Material.046']} />
      </group>
      <group position={[14.182, 5.175, 40.023]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-2.344, -0.661, -1.471]}>
        <mesh geometry={nodes.Cube163.geometry} material={materials['Material.058']} />
        <mesh geometry={nodes.Cube163_1.geometry} material={materials['Material.059']} />
        <mesh geometry={nodes.Cube163_2.geometry} material={materials['Material.060']} />
        <mesh geometry={nodes.Cube163_3.geometry} material={materials['Material.061']} />
      </group>
      <group position={[14.182, 5.175, 40.023]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-2.344, -0.661, -1.471]}>
        <mesh geometry={nodes.Cube165.geometry} material={materials['Material.063']} />
        <mesh geometry={nodes.Cube165_1.geometry} material={materials['Material.064']} />
        <mesh geometry={nodes.Cube165_2.geometry} material={materials['Material.065']} />
        <mesh geometry={nodes.Cube165_3.geometry} material={materials['Material.068']} />
      </group>
      <mesh geometry={nodes.Cube129.geometry} material={materials.table} position={[9.506, 1.653, 1.484]} rotation={[0, -Math.PI / 2, 0]} scale={[0.316, 1.268, 0.316]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['book.001']} position={[14.557, 11.566, -7.652]} scale={[1, 0.924, 1]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.book2} position={[9.223, 5.145, -8.231]} rotation={[0, 0.428, 0]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.shelf} position={[12.56, 3.834, -12.178]} scale={[2.078, 3.449, 2.078]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['book.001']} position={[11.862, 1.892, -11.333]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['book.001']} position={[12.56, 1.892, -13.047]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['book.001']} position={[12.657, 4.742, -13.411]} />
      <mesh geometry={nodes.Cube149.geometry} material={materials.bed} position={[3.108, 1.65, 10.013]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['leaf.001']} position={[-4.166, 7.599, 13.287]} rotation={[0, 0, -0.341]} scale={[0.09, 1.358, 0.381]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['leaf.002']} position={[13.618, 7.359, -7.62]} rotation={[0.148, 0.548, -0.355]} scale={[0.114, 1.876, 0.484]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['book2.001']} position={[13.987, 11.593, -10.236]} rotation={[0, -0.186, 0]} scale={[1.222, 1.058, 1.095]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['book2.001']} position={[14.171, 11.006, -10.313]} rotation={[0, 1.432, 0]} scale={[1.222, 1.058, 1.095]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['book2.002']} position={[1.108, 1.263, -9.12]} rotation={[0, -0.768, 0]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['book2.002']} position={[1, 0.74, -9.243]} rotation={[0, 1.094, 0]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['book2.003']} position={[1.059, 1.767, -9.069]} rotation={[-0.072, -1.107, -0.075]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['book2.004']} position={[1.059, 0.635, -3.419]} rotation={[-0.037, -0.545, -0.031]} scale={[1, 0.866, 0.896]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.009']} position={[12.203, 5.669, -3.53]} rotation={[0, -0.018, 0]} scale={[1.186, 1.186, 1.028]} />
      <mesh geometry={nodes.Cube099.geometry} material={nodes.Cube099.material} position={[-0.222, 9.199, -14.162]} scale={[5.177, 3.066, 0.147]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.044']} position={[15.216, 12.11, 9.901]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1, 0.678, 1.441]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.044']} position={[15.108, 10.414, -6.788]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.04, 1.04, 1.414]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.016']} position={[15.441, 7.634, 0.05]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-7.174, -0.314, -14.496]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.floor} position={[15.441, 7.634, 0.05]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-7.174, -0.314, -14.496]} />
    </group>
  )
}

useGLTF.preload('/models/playerRoom.gltf')
