/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Campfire.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Campfire(props) {
  const { nodes, materials } = useGLTF('/models/Campfire.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['campfire_01_Plane003-Mesh'].geometry} material={materials.FF5722} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh_1'].geometry} material={materials['78909C']} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh_2'].geometry} material={materials.FFCC88} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh_3'].geometry} material={materials.FFEB3B} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh_4'].geometry} material={materials['795548']} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh_5'].geometry} material={materials.CFD8DC} />
    </group>
  )
}

useGLTF.preload('/models/Campfire.glb')
