/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 test.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cemetery(props) {
  const { nodes, materials } = useGLTF('/models/Cemetery.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh geometry={nodes.Box064.geometry} material={materials['02___Default']} />
        <mesh geometry={nodes.Object012.geometry} material={materials._Cliff_123211___Default} />
        <mesh geometry={nodes.Box111.geometry} material={materials['03___Default']} />
        <mesh geometry={nodes.Box116_1.geometry} material={materials['03___Default']} />
        <mesh geometry={nodes.Box116_1_2.geometry} material={materials._Church_122109___Default} />
        <mesh geometry={nodes.Box116_1_3.geometry} material={materials._Church_1221Material} />
        <mesh geometry={nodes.Box116_1_4.geometry} material={materials._Cliff_123211___Default} />
        <mesh geometry={nodes.Box116_1_5.geometry} material={materials['01___Default']} scale={[5, 2, 5]} />
      </group>

    </group>
  )
}

useGLTF.preload('/models/Cemetery.glb')
