/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Desktop.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Desktop(props) {
  const { nodes, materials } = useGLTF('/models/Desktop.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[13.288, 7.927, -4.872]}>
        <mesh geometry={nodes.Cube080.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Cube080_1.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Cube080_2.geometry} material={materials['Material.039']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Desktop.gltf')
