/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Ground.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ground(props) {
  const { nodes, materials } = useGLTF('/models/Ground.gltf')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[3.698, -15.807, -3.215]} rotation={[-Math.PI, 0, -Math.PI]} scale={[400, 1, 400]} />
    </group>
  )
}

useGLTF.preload('/models/Ground.gltf')
