/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 5_1_Room.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MainRoom(props) {
  const { nodes, materials } = useGLTF('/models/5_1_Room.gltf')

  return (
    <group {...props} dispose={null}>
      <group position={[15.358, 0, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-7.65, -0.308, -14.467]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/5_1_Room.gltf')
