/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Shelf.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shelf(props) {
  const { nodes, materials } = useGLTF('/models/Shelf.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[12.177, 3.651, -13.359]} rotation={[-3.134, 0.002, 3.139]} scale={[1, 0.945, 1]}>
        <mesh geometry={nodes.Cube033.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube033_1.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cube033_3.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Cube033_4.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube033_5.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube033_6.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Cube033_7.geometry} material={materials['Material #2.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Shelf.gltf')
